# Generated by Django 6.0.1 on 2026-02-18 17:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(help_text='Unique employee identifier (e.g., EMP001)', max_length=20, unique=True)),
                ('full_name', models.CharField(help_text='Full name of the employee', max_length=150)),
                ('email', models.EmailField(help_text='Employee email address', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('department', models.CharField(choices=[('engineering', 'Engineering'), ('marketing', 'Marketing'), ('sales', 'Sales'), ('hr', 'Human Resources'), ('finance', 'Finance'), ('operations', 'Operations'), ('design', 'Design'), ('product', 'Product'), ('support', 'Customer Support'), ('other', 'Other')], help_text='Department the employee belongs to', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['-created_at'],
            },
        ),
    ]
